### ISSUE TITLE
group membership defined by fungible token

### ISSUE THREAD

**Issue by hxrts** [regen-network/cosmos-modules#76]
It should be possible to issue a sub-token that represents shareholder rights to a group. AFAIK in the current architecture this is not possible because the participating accounts must be defined in advance, correct me if I'm wrong.

**Comment by aaronc** [comment]
I think this is a duplicate of #75. This is something that we would like to see, but it is also pretty complex to implement because any given proposal would need a snapshot of the token balances at the voting time for the proposal. We need to figure out how to do that in an efficient, scalable way. By the way, this repo should be archived and these proposals should either go in https://github.com/regen-network/regen-ledger or https://github.com/cosmos/cosmos-sdk as my understanding is that we are moving it into the SDK relatively soon.

**Comment by hxrts** [comment]
Yeah, I wasn't sure. It seemed a little weird to make an issue on the regen ledger for this. Will close for now.
